Repository Goorm-third-project/seot-backend, pull requests merged in 2025-08, with the labels that each got.

#61 [Refactor] CustomUserDetails import 경로 수정
  src/main/java/com/example/backend/domain/alarm/controller/AlarmCommandController.java
  src/main/java/com/example/backend/domain/alarm/controller/AlarmQueryController.java
Labels: refactor

#68 [Fix] Swagger 접속 오류 해결
  src/main/java/com/example/backend/domain/global/exception/GlobalExceptionHandler.java
Labels: bug

#71 [Feat] 관리자 대시보드 기능 구현
  build.gradle
  src/main/java/com/example/backend/domain/admin/controller/AdminDashboardController.java
  src/main/java/com/example/backend/domain/admin/dto/AdminDashboardResponse.java
  src/main/java/com/example/backend/domain/admin/dto/MonthlyStoreVisitStats.java
  src/main/java/com/example/backend/domain/admin/dto/StoreEventVisitStats.java
  src/main/java/com/example/backend/domain/admin/service/AdminDashboardService.java
  src/main/java/com/example/backend/domain/auth/controller/AuthController.java
  src/main/java/com/example/backend/domain/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/example/backend/domain/auth/jwt/JwtTokenProvider.java
  src/main/java/com/example/backend/domain/auth/jwt/security/CustomUserDetails.java
  src/main/java/com/example/backend/domain/auth/jwt/security/CustomUserDetailsService.java
  src/main/java/com/example/backend/domain/auth/service/AuthService.java
  src/main/java/com/example/backend/domain/global/config/QuerydslConfig.java
  src/main/java/com/example/backend/domain/member/repository/MemberRepository.java
  src/main/java/com/example/backend/domain/store/entity/StoreDailyVisitor.java
  src/main/java/com/example/backend/domain/store/repository/StoreDailyVisitorCustom.java
  src/main/java/com/example/backend/domain/store/repository/StoreDailyVisitorRepository.java
  src/main/java/com/example/backend/domain/store/repository/StoreDailyVisitorRepositoryImpl.java
Labels: refactor, feature

#70 [Feat] 상점 이벤트 발생 시 해당 상점 좋아요한 회원에게 알림 전송 기능 구현
  src/main/java/com/example/backend/domain/alarm/controller/AlarmCommandController.java
  src/main/java/com/example/backend/domain/alarm/dto/AlarmResponse.java
  src/main/java/com/example/backend/domain/alarm/entity/Alarm.java
  src/main/java/com/example/backend/domain/alarm/entity/AlarmType.java
  src/main/java/com/example/backend/domain/alarm/service/command/AlarmCommandService.java
  src/main/java/com/example/backend/domain/alarm/service/command/AlarmCreateService.java
  src/main/java/com/example/backend/domain/alarm/service/command/AlarmReadService.java
  src/main/java/com/example/backend/domain/event/service/command/EventCreateService.java
  src/main/java/com/example/backend/domain/like/repository/StoreLikeRepository.java
  src/test/java/com/example/backend/domain/alarm/service/AlarmServiceTest.java
Labels: feature

#75 [Feat] 게시글 전체 조회 기능 구현
  src/main/java/com/example/backend/domain/post/controller/PostQueryController.java
  src/main/java/com/example/backend/domain/post/repository/PostRepository.java
  src/main/java/com/example/backend/domain/post/repository/PostRepositoryCustom.java
  src/main/java/com/example/backend/domain/post/repository/PostRepositoryImpl.java
  src/main/java/com/example/backend/domain/post/service/PostQueryService.java
Labels: feature
