Repository Goorm-third-project/seot-backend, pull requests merged in 2025-07, with the labels that each got.

#2 [Chore] spring data redis, AWS S3 의존성 추가
  build.gradle
Labels: setting

#5 [Feat] 인증/인가 적용 및 관련 의존성 추가
  build.gradle
  src/main/java/com/example/backend/domain/auth/controller/AuthController.java
  src/main/java/com/example/backend/domain/auth/dto/JwtToken.java
  src/main/java/com/example/backend/domain/auth/dto/SigninRequest.java
  src/main/java/com/example/backend/domain/auth/dto/SignupRequest.java
  src/main/java/com/example/backend/domain/auth/exception/AuthErrorCode.java
  src/main/java/com/example/backend/domain/auth/exception/AuthException.java
  src/main/java/com/example/backend/domain/auth/service/AuthService.java
  src/main/java/com/example/backend/domain/global/BaseEntity.java
  src/main/java/com/example/backend/domain/global/config/SecurityConfig.java
  src/main/java/com/example/backend/domain/global/exception/BaseException.java
  src/main/java/com/example/backend/domain/global/exception/ErrorCode.java
  src/main/java/com/example/backend/domain/global/exception/ErrorResponse.java
  src/main/java/com/example/backend/domain/global/exception/GlobalErrorCode.java
  src/main/java/com/example/backend/domain/global/exception/GlobalExceptionHandler.java
  src/main/java/com/example/backend/domain/global/success/GlobalSuccessCode.java
  src/main/java/com/example/backend/domain/global/success/SuccessCode.java
  src/main/java/com/example/backend/domain/global/success/SuccessResponse.java
  src/main/java/com/example/backend/domain/redis/config/JacksonConfig.java
  src/main/java/com/example/backend/domain/redis/config/RedisConfig.java
  src/main/java/com/example/backend/domain/redis/listener/AuthenticationEventListener.java
  src/main/java/com/example/backend/domain/redis/model/ActiveUser.java
  src/main/java/com/example/backend/domain/redis/service/ActiveUserService.java
  src/main/java/com/example/backend/domain/security/adapter/CustomUserDetails.java
  src/main/java/com/example/backend/domain/security/adapter/CustomUserDetailsService.java
  src/main/java/com/example/backend/domain/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/example/backend/domain/security/jwt/JwtTokenProvider.java
  src/main/java/com/example/backend/domain/security/jwt/entity/RefreshToken.java
  src/main/java/com/example/backend/domain/security/jwt/repository/RefreshTokenRepository.java
  src/main/java/com/example/backend/domain/user/entity/Role.java
  src/main/java/com/example/backend/domain/user/entity/Users.java
  src/main/java/com/example/backend/domain/user/repository/UserRepository.java
Labels: feature

#11 [Feat] Alarm 구조 설계
  src/main/java/com/example/backend/BackendApplication.java
  src/main/java/com/example/backend/domain/alarm/controller/AlarmController.java
  src/main/java/com/example/backend/domain/alarm/entity/Alarm.java
  src/main/java/com/example/backend/domain/alarm/service/AlarmService.java
  src/main/java/com/example/backend/domain/global/config/SecurityConfig.java
  src/main/java/com/example/backend/domain/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/example/backend/domain/user/entity/Role.java
  src/main/resources/application-local.yml
Labels: feature

#21 [Feat] Alarm 기능 확장
  src/main/java/com/example/backend/domain/alarm/controller/AlarmController.java
  src/main/java/com/example/backend/domain/alarm/dto/AlarmResponse.java
  src/main/java/com/example/backend/domain/alarm/entity/Alarm.java
  src/main/java/com/example/backend/domain/alarm/repository/AlarmRepository.java
  src/main/java/com/example/backend/domain/alarm/service/AlarmService.java
  src/test/java/com/example/backend/domain/alarm/service/AlarmServiceTest.java
Labels: feature

#28 [Refactor] Alarm 코드 개선
  src/main/java/com/example/backend/domain/alarm/entity/Alarm.java
  src/main/java/com/example/backend/domain/alarm/repository/AlarmRepository.java
  src/main/java/com/example/backend/domain/alarm/service/AlarmService.java
  src/test/java/com/example/backend/domain/alarm/service/AlarmServiceTest.java
  src/test/java/com/example/backend/support/fixture/AlarmFixture.java
Labels: refactor

#33 [Fix] Credential Providers 오류
  Jenkinsfile
Labels: bug

#50 [Refactor] Alarm CQRS 패턴 분리
  src/main/java/com/example/backend/domain/alarm/controller/AlarmCommandController.java
  src/main/java/com/example/backend/domain/alarm/controller/AlarmController.java
  src/main/java/com/example/backend/domain/alarm/controller/AlarmQueryController.java
  src/main/java/com/example/backend/domain/alarm/dto/AlarmResponse.java
  src/main/java/com/example/backend/domain/alarm/repository/EmitterRepository.java
  src/main/java/com/example/backend/domain/alarm/service/AlarmQueryService.java
  src/main/java/com/example/backend/domain/alarm/service/command/AlarmCommandService.java
  src/main/java/com/example/backend/domain/alarm/service/command/AlarmCreateService.java
  src/main/java/com/example/backend/domain/alarm/service/command/AlarmDeleteService.java
  src/main/java/com/example/backend/domain/alarm/service/command/AlarmReadAllService.java
  src/main/java/com/example/backend/domain/global/config/SecurityConfig.java
  src/test/java/com/example/backend/domain/alarm/service/AlarmServiceTest.java
  src/test/resources/application-test.yml
Labels: refactor
